/**
 * This class file was automatically generated by jASN1 v1.8.0 (http://www.openmuc.org)
 */

package org.onosproject.xran.asn1lib.api;

import org.onosproject.xran.asn1lib.ber.*;
import org.onosproject.xran.asn1lib.ber.types.*;
import org.onosproject.xran.asn1lib.ber.types.string.*;

import java.math.BigInteger;


public class RXSigMeasRepInterval extends BerEnum {

	private static final long serialVersionUID = 1L;

	public RXSigMeasRepInterval() {
	}

	public RXSigMeasRepInterval(byte[] code) {
		super(code);
	}

	public RXSigMeasRepInterval(BigInteger value) {
		super(value);
	}

	public RXSigMeasRepInterval(long value) {
		super(value);
	}

}
